#!/bin/bash

chown root:wheel /etc/
chmod 755 /etc/Freedom
chown root:wheel /etc/Freedom/minimalhosts
chmod 644 /etc/Freedom/minimalhosts
chown root:wheel /etc/Freedom/defaulthosts
chmod 644 /etc/Freedom/defaulthosts
echo "Overwriting hosts file..."
cp -a /etc/Freedom/minimalhosts /etc/hosts
echo "Overwrite complete!"
chown root:wheel /etc/hosts
chmod 644 /etc/hosts
echo "Killing discoveryd/mDNSResponder..."
killall -9 discoveryd
killall -9 mDNSResponder
echo "Should have died and restarted by now..."
echo "Deleting .git folder..."
rm -rf .git
echo ".git folder deleted!"
echo "Enjoy Freedom!"
exit 0
